# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:33
from __future__ import unicode_literals

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import kommunabokhald.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('reason', models.CharField(default='', max_length=200)),
                ('housemates_this_month', models.IntegerField(default=kommunabokhald.models.get_total_housemates)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_rent', models.IntegerField()),
                ('house_fund', models.IntegerField()),
                ('electricity', models.IntegerField()),
                ('internet', models.IntegerField()),
                ('gagnaveitan', models.IntegerField()),
                ('house_reparations', models.IntegerField()),
                ('housemates_this_month', models.IntegerField(default=kommunabokhald.models.get_total_housemates)),
            ],
        ),
        migrations.CreateModel(
            name='Housemate',
            fields=[
            ],
            options={
                'proxy': True,
                'ordering': ('first_name',),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kommunabokhald.Housemate'),
        ),
    ]
